export const CHANGE_FORM = "SZKOLENIE::CHANGE_FORM";
export const TOUCH_FORM = "SZKOLENIE::TOUCH_FORM";
export const FOCUS_FORM = "SZKOLENIE::FOCUS_FORM";
export const TOUCH_ALL = "SZKOLENIE::TOUCH_ALL";
