export const CHANGE_FORM = "SZKOLENIE::CHANGE_FORM";
export const TOUCH_FORM = "SZKOLENIE::TOUCH_FORM";
export const FOCUS_FORM = "SZKOLENIE::FOCUS_FORM";
export const TOUCH_ALL = "SZKOLENIE::TOUCH_ALL";

export const SEND_EMAIL = "SZKOLENIE::SEND_EMAIL";
export const SEND_EMAIL_SUCCESS = "SZKOLENIE::SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SZKOLENIE::SEND_EMAIL_FAILURE";
export const RESET_FORM = "SZKOLENIE::RESET_FORM";
