export const CHANGE_FORM = "KONTAKT::CHANGE_FORM";
export const TOUCH_FORM = "KONTAKT::TOUCH_FORM";
export const FOCUS_FORM = "KONTAKT::FOCUS_FORM";
export const TOUCH_ALL = "KONTAKT::TOUCH_ALL";

export const SEND_EMAIL = "KONTAKT::SEND_EMAIL";
export const SEND_EMAIL_SUCCESS = "KONTAKT::SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "KONTAKT::SEND_EMAIL_FAILURE";

export const RESET_FORM = "KONTAKT::RESET_FORM";
