export const NAVIGATE_TO = 'ROOT::NAVIGATE_TO';
export const GET_PAGE_CONTENT = 'ROOT::GET_PAGE_CONTENT';
export const GET_PAGE_CONTENT_SUCCESS = 'ROOT::GET_PAGE_CONTENT_SUCCESS';
export const GET_PAGE_CONTENT_FAILURE = 'ROOT::GET_PAGE_CONTENT_FAILURE';
