export const LOGIN_CHANGE_USER_LOGIN = 'LOGIN_CHANGE_USER_LOGIN';
export const LOGIN_CHANGE_USER_PASSWORD = 'LOGIN_CHANGE_USER_PASSWORD';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
